### ISSUE TITLE
Code Review: Refactor `set_data`

### ISSUE THREAD

**Issue by Askaholic** [FAForever/faf-scfa-replay-parser#1]
https://github.com/FAForever/faf-scfa-replay-parser/blob/28e104325090037ede31febbb95cd21c83207d82/replay_parser/reader.py#L138

1. Add `:param:` to the docstrings.
2. Switch `no_copy_source_data=False` (double negative) to `copy_source=True` and switch the check logic
3. Make functions for each different type of input (`(RawIOBase, BytesIO, FileIO) or (bytes, bytearray)`), so that `set_data` just resolves types and calls appropriate function or raises `ValueError`

**Comment by norraxx** [comment]
1) Done.
2) `no_copy_data_source` is bad technique, I've removed it. You wanna behave immutable like, so no need to work with  source object, make your own, and copy the data, otherwise you, as library, could replace data for others. For example: sqlalchemy behaves like that in every call of each method.
3) Done. Also after the splitting the methods I've found the place, where we can speed up the code by 15% just by using one of that methods.
